### PR TITLE
[BACKEND] Implementing Password Change Endpoint

### LINKED ISSUE #415: Implement Password Change Endpoint
I will implement an endpoint that lets users to change their previous passwords.

### PR DESCRIPTION
**Pull request by omerfdeniz**
## Type of change

- [X] New feature (non-breaking change which adds functionality)

# Description

I implemented the password change feature for the users of the system.

Logged in users can POST the following body to /changepassword path in the system to change their password.

Input Format:

```
{
    "password": "current_password_here",
    "new_password": "new_password_here"
}
```

# Test results

```
(djangoenv) (base) omer-mbp:backend omer$ python manage.py test API.tests.TestAccount.test_password_change
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.
----------------------------------------------------------------------
Ran 1 test in 0.128s

OK
Destroying test database for alias 'default'...
(djangoenv) (base) omer-mbp:backend omer$ python manage.py test API.tests.TestAccount.test_password_change_with_wrong_password
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.
----------------------------------------------------------------------
Ran 1 test in 0.087s

OK
Destroying test database for alias 'default'...
(djangoenv) (base) omer-mbp:backend omer$ python manage.py test API.tests.TestAccount.test_password_change_without_login
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.
----------------------------------------------------------------------
Ran 1 test in 0.041s

OK
Destroying test database for alias 'default'...
```

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have checked my code and corrected any misspellings
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by umutoksuz — APPROVED** [review]
Looks good!

**Review by bekir96 — APPROVED** [review]
All work seems good and no change required for this endpoint

**Review by furkannane — APPROVED** [review]
Things seem to be working smoothly

**Review by bcetin — APPROVED** [review]
Properly commented and well implemented.

**Pull request merged**
