### PR TITLE
Price conversion using user's IP (locationcurrencyapi)

### PR DESCRIPTION
**Pull request by ozdenizdolu**
We have added the route `/api/getConvertedPrice` to our API.

This route gets an IP adress, finds its the currency of the country that this IP adress belongs to. It also gets a price in some currency. Then converts the price into the new currency (one that belongs to the IP adress) using the up to date exchange rates. Responses the conversion result.

It accepts a GET Request with 3 parameters:

- ip: any valid ip adress
- price: a number representing the price
- srcCurrency: a currency code (TRY for example)

It responds with 2 pieces of information:

- price: converted price
- currency: currency of the new price

We added unit tests for our functions. Our code is compatible with all the unit tests up until now.

We also added a small demonstration in the index.js page. You click a button and see the result of the conversion on 10 USD price.

### CODE REVIEW

**Comment by MehdiSaffar** [comment]
I quickly glanced over the code and it looks very well written. Good job!
I would suggest adding a reviewer outside of your subgroup though.

**Comment by ozdenizdolu** [comment]
Thanks for the review! You can make a full review if you want, I have added @furkannane as a reviewer too.

**Comment by furkannane** [comment]
I am actually fluttered to be chosen as a reviewer but the truth is i barely wrote my own code :) I dont think i can say anything meaningful :)

**Comment by ozdenizdolu** [comment]
Haha okay! I didn't want to call Mehdi because i get a feeling that every subgroup will pick Mehdi as a reviewer. I didn't want to put too much burden on him :)

**Comment by furkannane** [comment]
You are on point with that thought.

**Review by furkannane — APPROVED** [review]
Seems to be working fine.

**Comment by ozdenizdolu** [comment]
Thank you for your reviews on the previous pull request @MehdiSaffar and your reviews on this request @furkannane. I have merged the request with no problems.

**Comment by handesirikci** [comment]
i also reviewed and it works properly. Test cases include every possible scenario, it passes all of them.

**Pull request merged**
