### PR TITLE
[FRONTEND] F product card improvements

### LINKED ISSUE #217: [FRONTEND] Improve product card
- fix image size
 - put image in fixed size container (even before image loaded)
 - maybe redo it with CSS grid as it is easier
 - show price more prominently

### PR DESCRIPTION
**Pull request by abdullahyldz**
## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

# Description

Antd component Card is removed and `` HTML tag is added. 
New look of the product cards, see below for images.

# Screenshots

image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have checked my code and corrected any misspellings
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# Potential problems/Important remarks

There is a problem with long title texts, I couldn't make "text-overflow : ellipsis " style work.
image
image

Closes #217

### CODE REVIEW

**Review by ozdenizdolu — APPROVED** [review]
I think it looks good.

**Comment by ozdenizdolu** [comment]
with regard to your problem, we should to decide on a "max title length" for products and if it's still too much, maybe you can make the card a little bit longer in height?

**Comment by abdullahyldz** [comment]
> with regard to your problem, we should to decide on a "max title length" for products and if it's still too much, maybe you can make the card a little bit longer in height?



> with regard to your problem, we should to decide on a "max title length" for products and if it's still too much, maybe you can make the card a little bit longer in height?

You are right, I wrote some limiting height but it only restricted `<div>`, not `<p>`
Somehow, `<p>` exceeded the limit. 

I hid the overflowing text behind the rate and price part. 

image
image

**Comment by MehdiSaffar** [comment]
I will review this tonight

**Review by MehdiSaffar — COMMENTED** [review]
It looks good. There were some minor issues with width/height and the buttons, I adjusted those with @ozdenizdolu in a google meet. Also I added a nonfunctioning wish list button right next to the add to cart button, and made the buttons larger.

I would suggest that you do the ellipsis thing with javascript directly when you are rendering the title (checkout stackoverflow for that for a ready solution).

Also imagine that some of the products will have a discount so maybe you can show the old price with a strikethrough on the left and the new price in a bold font on the right.

Example:

image

Also could you please show the rating in decimals right next to the stars? Make sure not to allow more than 1 decimal place (otherwise you might end up with weird number slike 1.666666666666669)

Otherwise good job, I like it :)

**Pull request merged**
