### PR TITLE
[BACKEND] GET user/<int:id>/listShoppingCart/ and product/<int:productId>/ endpoints

### PR DESCRIPTION
**Pull request by omerfdeniz**
## Type of change

- [x ] New feature (non-breaking change which adds functionality)

# Description
I added user/<int:id>/listShoppingCart/ and product/<int:productId>/ endpoints. Former lists the items in the user's shopping cart and the latter gives the details of the given product.

# Test results

```
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..
----------------------------------------------------------------------
Ran 2 tests in 0.086s

OK
Destroying test database for alias 'default'...
```

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have checked my code and corrected any misspellings
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Important:

While we are creating the db models in Django, name field was added to ShoppingCartItem which is not present in our db schema so I removed it.

### CODE REVIEW

**Comment by bekir96** [comment]
can you add ' from .shopping_cart import * ' to __init__.py in the views folder

**Review by furkannane — APPROVED** [review]
Thank you for modulerazing the code. It looks fine.

**Comment by bekir96** [comment]
Shows that conflicts, can you resolve?

**Comment by omerfdeniz** [comment]
Resolved all of the conflicts.

**Pull request merged**
